name: Build

on:
    push:
        branches: [ master ]
    pull_request:
    release:
        types: [ created ]

jobs:
    tests:
        runs-on: ubuntu-latest
        name: Build and test
        strategy:
            fail-fast: false
            matrix:
                php: [ "7.3" ]
                composer-version: [ "1" ]
                coverage: [ "none" ]
                publish-phar: [ false ]
                phar-readonly: [ false ]
                git-fetch-depth: [ 1 ]
                dependencies: [ "locked" ]
                include:
                    -   php: "7.2"
                        composer-version: "1"
                        git-fetch-depth: 1
                        dependencies: "lowest"
                    -   php: "7.3"
                        composer-version: "1"
                        phar-readonly: true
                        git-fetch-depth: 1
                        dependencies: "locked"
                    -   php: "7.4"
                        composer-version: "1"
                        coverage: "pcov"
                        publish-phar: true
                        git-fetch-depth: 0 # box/composer needs history to determine a recent git version
                        dependencies: "locked"
                    -   php: "7.4"
                        composer-version: "2"
                        git-fetch-depth: 1
                        dependencies: "locked"

        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: "${{ matrix.git-fetch-depth }}"

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    ini-values: "phar.readonly=0"
                    tools: "composer:v${{ matrix.composer-version }}"
                    coverage: "${{ matrix.coverage }}"

            -   name: Get composer cache directory
                id: composercache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache composer dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composercache.outputs.dir }}
                    key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-cache-

            -   name: "Install lowest dependencies"
                if: matrix.dependencies == 'lowest'
                run: composer update --prefer-lowest --no-interaction --no-progress --no-suggest --prefer-dist

            -   name: "Install locked dependencies"
                if: matrix.dependencies == 'locked'
                run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

            -   name: Install requirement-checker dependencies
                run: composer install --no-interaction --no-progress --no-suggest --prefer-dist --working-dir requirement-checker

            -   name: validate box config
                run: bin/box validate

            -   name: Run tests (coverage)
                if: matrix.coverage == 'pcov'
                run: make tm

            -   name: Run tests (phar readonly)
                if: matrix.phar-readonly == true
                run: make tu_box_phar_readonly

            -   name: Run tests
                if: matrix.coverage != 'pcov' && matrix.phar-readonly != true
                run: make test

            -   uses: actions/upload-artifact@v1
                name: Publish the PHAR
                if: matrix.publish-phar == true
                with:
                    name: box.phar
                    path: bin/box.phar

    publish-phar:
        runs-on: ubuntu-latest
        name: Publish the PHAR
        needs: tests
        if: github.event_name == 'release'
        steps:
            -   uses: actions/download-artifact@v1
                with:
                    name: box.phar
                    path: .

            -   name: Upload box.phar
                uses: actions/upload-release-asset@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ github.event.release.upload_url }}
                    asset_path: box.phar
                    asset_name: box.phar
                    asset_content_type: application/zip
